### ISSUE TITLE
Petitions Role Ping

### ISSUE THREAD

**Issue by sylviameows** [sylviameows/amayi#2]
When running the petitions command in the petitions channel the message doesn't ping.
I believe this is caused by the petition being an edited message instead of a new message so one solution could be creating a new message when the petition is sent instead of editing the deferred reply.

**Comment by Restitutor** [comment]
Editing deferred reply could be nice since it'll show the slash command being run. Another idea is ghost ping and delete the message

**Comment by sylviameows** [comment]
editing deffered reply is whats causing this problem atm. but now that you mention it i have an idea to fix this

**Comment by sylviameows** [comment]
fix completed, creating a petition in the petitions channel should now role ping properly.
