### ISSUE TITLE
Remove amayi petition reactions when no longer required

### ISSUE THREAD

**Issue by Restitutor** [sylviameows/amayi#3]
When a user reacts with upvotes or downvotes we should add the following logic to let Amayi remove its own reaction.

1. Check if the message has at least 3 upvotes and downvotes including Amayi.
2. Remove Amayi's reactions.

We could check if it's at least 2, but then a user may remove their reaction and break the order.

**Comment by Restitutor** [comment]
Good first issue for someone to practice contributing

**Comment by sylviameows** [comment]
ooh yeah i should do this at some point ~~when i rework amayi for the Xth time.~~, but its not on my list of things to do right now so if someone would like to implement this feel free

**Comment by sylviameows** [comment]
side note: implemented solution does not work with number petitions, so this could be reopened in the future if someone would like to work on that.
